-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN     "platformFee" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalJobAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "workshopRevenue" DOUBLE PRECISION NOT NULL DEFAULT 0;
